# Generated by Django 5.2.7 on 2025-10-09 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('job_type', models.CharField(choices=[('full-time', 'Full Time'), ('part-time', 'Part Time'), ('contract', 'Contract'), ('temporary', 'Temporary')], max_length=20)),
                ('category', models.CharField(choices=[('construction', 'Construction'), ('education', 'Education'), ('hospitality', 'Hospitality'), ('retail', 'Retail'), ('healthcare', 'Healthcare'), ('other', 'Other')], max_length=50)),
                ('vacancies', models.PositiveIntegerField(default=1)),
                ('salary', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
