# Generated by Django 5.2.7 on 2025-10-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localconnect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='contact',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='vacancies',
            field=models.IntegerField(),
        ),
    ]
