# Generated by Django 5.2.7 on 2025-10-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localconnect', '0009_rename_chatroom_message_room_remove_chatroom_user1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
